### ISSUE TITLE
"debug_appender" no such field

### ISSUE THREAD

**Issue by hohl** [optimatika/ojAlgo-finance#6]
It looks like okAlgo dropped the `debug_append` field. The `okAlgo-finance 1.0.0` works fine with `okAlgo 44.0.0` but is broken with `okAlgo 45.1.0`.

```
java.lang.NoSuchFieldError: debug_appender

	at org.ojalgo.finance.portfolio.MarkowitzModel.calculateAssetWeights(MarkowitzModel.java:226)
	at org.ojalgo.finance.portfolio.EquilibriumModel.getAssetWeights(EquilibriumModel.java:86)
	at org.ojalgo.finance.portfolio.EquilibriumModel.getWeights(EquilibriumModel.java:134)
```

**Comment by apete** [comment]
Yes, the released v1.0.0 depends on ojAlgo v44.0.0, and is incompatible with later versions.

I just now built and released v1.1.0 that should work fine with ojAlgo v45.1.0.

I'll close this issue now. If there are further problems you can re-open it.
